version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_reservation_system
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test
